version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-app
    ports:
      - '${PORT}:${PORT}' 
    environment:
      PORT: ${PORT} 
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:${MONGO_PORT}

